"""2

Revision ID: 71e2a5b210ab
Revises: 99ab80cb7d22
Create Date: 2023-05-31 13:04:02.417964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e2a5b210ab'
down_revision = '99ab80cb7d22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
